In [4]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [5]:
import pandas as pd
from matplotlib import pyplot as plt

In [6]:
df1 = pd.read_excel('Online Retail.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'Online Retail.xlsx'

In [ ]:
df1.shape

In [ ]:
df1.info()

#### Data Cleaning : Handling missing values ####

In [ ]:
df1.isnull().sum() # this shows number of Na records per column

In [ ]:
df1[df1.Description.isnull()] # records which have null Description

In [ ]:
df1[df1.StockCode == '22139'].Description.mode()

In [ ]:
most_freq = df1[['StockCode' , 'Description']].value_counts().reset_index()
most_freq

In [ ]:
most_freq[most_freq.StockCode == '85123A']

In [ ]:
most_freq[most_freq.StockCode == '85123A'].head(1)

  StockCode                         Description   count
0    85123A  WHITE HANGING HEART T-LIGHT HOLDER  138120

In [ ]:
most_freq = most_freq.groupby("StockCode").head(1)
most_freq

     StockCode                         Description   count
0       85123A  WHITE HANGING HEART T-LIGHT HOLDER  138120
1        22423            REGENCY CAKESTAND 3 TIER  132000
2       85099B             JUMBO BAG RED RETROSPOT  129540
3        47566                       PARTY BUNTING  103620
4        20725             LUNCH BAG RED RETROSPOT   98280
...        ...                                 ...     ...
4764     90048          GREEN WITH METAL BAG CHARM      60
4777    84802B    PURPLE ANEMONE ARTIFICIAL FLOWER      60
4778    84743C                             damages      60
4790    84803A      PINK ALLIUM  ARTIFICIAL FLOWER      60
4791    84795C               OCEAN STRIPE HAMMOCK       60

[3958 rows x 3 columns]

In [ ]:
most_freq.columns = ['StockCode' , 'freq_Description' , 'count']
df2 = df1.merge(most_freq , on= 'StockCode' , how = 'left')
df2

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,freq_Description,count
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,WHITE HANGING HEART T-LIGHT HOLDER,138120.0
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,WHITE METAL LANTERN,19680.0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,CREAM CUPID HEARTS COAT HANGER,17580.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,KNITTED UNION FLAG HOT WATER BOTTLE,28380.0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,RED WOOLLY HOTTIE WHITE HEART.,26940.0
...,...,...,...,...,...,...,...,...,...,...
32514535,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,PACK OF 20 SPACEBOY NAPKINS,8880.0
32514536,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,CHILDREN'S APRON DOLLY GIRL,19200.0
32514537,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,CHILDRENS CUTLERY DOLLY GIRL,18420.0
32514538,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,CHILDRENS CUTLERY CIRCUS PARADE,9720.0
32514539,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,BAKING SET 9 PIECE RETROSPOT,58440.0

In [ ]:
df2['Description'] = df2['freq_Description']

In [ ]:
df2.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,freq_Description,count
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,WHITE HANGING HEART T-LIGHT HOLDER,138120.0
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,WHITE METAL LANTERN,19680.0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,CREAM CUPID HEARTS COAT HANGER,17580.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,KNITTED UNION FLAG HOT WATER BOTTLE,28380.0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,RED WOOLLY HOTTIE WHITE HEART.,26940.0

In [ ]:
df2.isnull().sum()

InvoiceNo                 0
StockCode                 0
Description            6720
Quantity                  0
InvoiceDate               0
UnitPrice                 0
CustomerID          8104800
Country                   0
freq_Description       6720
count                  6720
dtype: int64

In [ ]:
df2.dropna(subset = ['Description'], inplace = True)
df2.isnull().sum()

InvoiceNo                 0
StockCode                 0
Description               0
Quantity                  0
InvoiceDate               0
UnitPrice                 0
CustomerID          8098080
Country                   0
freq_Description          0
count                     0
dtype: int64

In [ ]:
df2.drop(columns = ['freq_Description' , 'count'] , inplace = True)
df2.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
df2.describe()

           Quantity                    InvoiceDate     UnitPrice    CustomerID
count  3.250782e+07                       32507820  3.250782e+07  2.440974e+07
mean   9.555919e+00  2011-07-04 14:06:48.671256832  4.612067e+00  1.528769e+04
min   -8.099500e+04            2010-12-01 08:26:00 -1.106206e+04  1.234600e+04
25%    1.000000e+00            2011-03-28 11:36:00  1.250000e+00  1.395300e+04
50%    3.000000e+00            2011-07-20 08:59:00  2.080000e+00  1.515200e+04
75%    1.000000e+01            2011-10-19 11:41:00  4.130000e+00  1.679100e+04
max    8.099500e+04            2011-12-09 12:50:00  3.897000e+04  1.828700e+04
std    2.181032e+02                            NaN  9.676974e+01  1.713598e+03

In [ ]:
df2[df2.Quantity < 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
32513080,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
32514172,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
32514346,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
32514347,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
32514348,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [ ]:
df2[df2.UnitPrice < 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom
841892,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
841893,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom
1383801,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
31188797,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom
31730705,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
31730706,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom
32272614,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
32272615,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [ ]:
df3 = df2[(df2.UnitPrice > 0) & (df2.Quantity>0)]

In [ ]:
df3.describe()

           Quantity                    InvoiceDate     UnitPrice    CustomerID
count  3.180624e+07                       31806240  3.180624e+07  2.387304e+07
mean   1.054204e+01  2011-07-04 20:16:05.225086720  3.907625e+00  1.529442e+04
min    1.000000e+00            2010-12-01 08:26:00  1.000000e-03  1.234600e+04
25%    1.000000e+00            2011-03-28 12:22:00  1.250000e+00  1.396900e+04
50%    3.000000e+00            2011-07-20 12:58:00  2.080000e+00  1.515900e+04
75%    1.000000e+01            2011-10-19 12:39:00  4.130000e+00  1.679500e+04
max    8.099500e+04            2011-12-09 12:50:00  1.354133e+04  1.828700e+04
std    1.555240e+02                            NaN  3.591565e+01  1.713139e+03

In [ ]:
df3.Quantity.quantile(0.99)

np.float64(100.0)

In [ ]:
df3[df3.Quantity > 1500].head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
4850,536809,84950,ASSORTED COLOUR T-LIGHT HOLDER,1824,2010-12-02 16:48:00,0.55,15299.0,United Kingdom
4945,536830,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2880,2010-12-02 17:38:00,0.18,16754.0,United Kingdom
25920,538420,17096,ASSORTED LAQUERED INCENSE HOLDERS,1728,2010-12-12 12:03:00,0.17,12875.0,United Kingdom

#### Feature Engineering | Create new Column ####

In [ ]:
df4 = df3.copy()

In [ ]:
df4['Total_Sale'] = df4.Quantity * df4.UnitPrice

In [ ]:
df4.head(3)

In [ ]:
df4.info()

In [ ]:
df4['Month'] = df4['InvoiceDate'].dt.month

In [ ]:
df4.sample(5)

#### Visulization and EDA ####

##### PLot Monthly Sales

In [ ]:
Monthly_sales = df4.groupby("Month")['Total_Sale'].sum()

In [ ]:
Monthly_sales.plot(kind='line' , title = 'Monthly Sales' , marker = 'o')
plt.ylabel("Total Sales")
plt.grid()
plt.show()

**Insights **
Total sales started rising up in August having a peak in November . This is like due to holiday season at the end of the year

##### Top 5 Countries #####

In [ ]:
Country_wise_sales = df4.groupby("Country")['Total_Sale'].sum()
total_sales = Country_wise_sales.sum()

top_5_Countries = Country_wise_sales.sort_values(ascending = False).head(5)
percentage_contribution = (top_5_Countries / total_sales) * 100

plt.figure(figsize=(10,8))
bars = plt.barh(percentage_contribution.index , percentage_contribution.values)

for bar , percentage in zip(bars , percentage_contribution):
  plt.text(bar.get_width() + 1 , bar.get_y() + bar.get_height()/2 , f'{percentage:.1f}%', va = 'center' , ha = 'left')

plt.title('top 5 Countries by total sales')
plt.xlabel('percentage_contribution')
plt.ylabel('Countries')
plt.grid(axis = 'x')
plt.show()

In [ ]:
top_5_Countries

##### Product wise Sales #####

In [ ]:
product_wise_sales = df4.groupby('StockCode')['Total_Sale'].sum()
top_5_products = product_wise_sales.sort_values(ascending = False).head(5)
top_5_products.plot(kind = 'barh' , color = 'skyblue')
plt.title('Product Wise Sales')
plt.xlabel('Total Sales')
plt.ylabel('Product StockCode')
plt.gca().invert_yaxis() # to show the highest sales at the top
plt.show()

In [ ]:
product_wise_sales.sort_values(ascending = False)

In [ ]:
df4[df4.StockCode == "DOT"]

In [ ]:
for Stock_code in top_5_products.index:
  description = df4[df4.StockCode == Stock_code].Description.iloc[0]
  print(f"{Stock_code} ==> {description}")

##### RFM Analysis #####

In [ ]:
df4['InvoiceDate'].max()

In [ ]:
current_dt = df4['InvoiceDate'].max() + pd.Timedelta(days = 1)
current_dt

In [ ]:
rfm = df4.groupby("CustomerID").agg({
    'InvoiceDate' : lambda x : (current_dt - x.max()).days,
    'InvoiceNo' : 'count',
    'Total_Sale' : 'sum'
})
rfm.columns = ['Recency' , 'Frequency' , 'Monetary']
rfm.head(10)

In [ ]:
df4[df4.CustomerID == 12347]['Total_Sale'].sum()

In [ ]:
rfm['R_Segment']= pd.qcut(rfm['Recency'] , 4 ,labels=[4,3,2,1])
rfm['F_Segment'] = pd.qcut(rfm['Frequency'], 4 , labels = [1,2,3,4])
rfm['M_Segment'] = pd.qcut(rfm['Monetary'] , 4 , labels = [1,2,3,4])
rfm['RFM_Score'] = rfm[['R_Segment' , 'F_Segment' , 'M_Segment']].sum(axis= 1)

In [ ]:
rfm

In [ ]:
# qcut() function it will take a column and it will cut that into four quaartile and these are the labels

In [ ]:
rfm.drop(columns=['F_Segment'] , inplace = True)
rfm

In [ ]:
rfm.sort_values("RFM_Score" , ascending=False)

#### Customer Churn Analysis ####

In [ ]:
 df4.head(2)

In [ ]:
Customer_last_purchase = df4.groupby('CustomerID')['InvoiceDate'].max()
Customer_last_purchase.head()

In [ ]:
type(Customer_last_purchase)

In [ ]:
Customer_last_purchase = (current_dt - Customer_last_purchase).dt.days
Customer_last_purchase.head(10)

In [ ]:
# Define churn threshold(e.g , 90 days without purchase)
churn_threshold = 90
churned_customers = Customer_last_purchase[Customer_last_purchase > churn_threshold]
churned_customers.head(10)

In [ ]:
plt.figure(figsize=(10,6))
plt.hist(Customer_last_purchase , bins=50 , color = 'red' , alpha= 0.7)
plt.axvline(churn_threshold , color = 'black' , linestyle = 'dashed' , linewidth = 2)
plt.title("Customer Churn Distribution")
plt.xlabel("Days since last purchase")
plt.ylabel("Number of Customers")
plt.grid()
plt.show()

In [ ]:
import time
stime = time.time()
print(f"[{pd.__name__}] total time taken : {time.time() - stime} sec")